version: "3"

services:
  rest-api:
    container_name: bookshelf_api
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./config:/opt/app/config
  database:
    image: mysql
    build: ./database
    container_name: bookshelf_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=api
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bookshelf
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
